[package]
name = "newsletter"
version = "0.1.0"
edition = "2021"
authors = ["Felipe Torres González <torresfelipex1@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"

[dev-dependencies]
reqwest = "0.12.3"