#! configuration/base.yaml
application:
  port: 9090
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "https://api.postmarkapp.com"
  sender_email: "admin@nubecita.eu"
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000